spring:
  application:
    name: config-server
  profiles:
    active:
      - native

  cloud:
    config:
      server:
        #Local configuration : This locations can either of classpath or locations in the filesystem
        native:
          #Reads from a specific filesystem folder
          search-locations: classpath:/config
server:
  port: 8071


#When we run a Spring Cloud Config Server, it automatically exposes
#endpoints to server configuration properties to client applications.
#Example
#http://localhost:8071/licensing-service/dev -> gives dev and default properties
#http://localhost:8071/licensing-service/default -> only default one